### ISSUE TITLE
Prefixing `db_table` breaks models with long names.

### ISSUE THREAD

**Issue by mrmachine** [edoburu/django-fluent-pages#103]
Django will not allow a default `db_table` longer than the backend/connection allows. Fluent is explicitly assigning a `db_table` (to give it a prefix), which is disabling this truncation by Django.

I think Django should probably still truncate it to the max length allowed by the connection, even if it is explicitly set. Presumably there is no way for a table to exist in the database with a name that is longer than the max length.

However, it would take a while to get that change into Django and it probably wouldn't be backported to 1.7, 1.8, 1.9.

So, `django-fluent-contents` and `django-fluent-pages` should both do what Django does, and truncate the prefixed table name. Here are the offending lines:

https://github.com/edoburu/django-fluent-contents/blob/44154533c347b2985c28627cb15e4cdf7c441e76/fluent_contents/models/db.py#L177

and:

https://github.com/edoburu/django-fluent-pages/blob/master/fluent_pages/models/db.py#L55

And here's the Django code:

https://github.com/django/django/blob/7bb373e3097fe8e000e0bba005ff2dcfc18ab9a5/django/db/models/options.py#L214-L217

That Django code has been around for a long time, so it should work for all supported versions of Django, and probably several older versions too.

**Comment by vdboor** [comment]
I've merged both commits now, thanks for this useful fix!
