### ISSUE TITLE
Sidemenu trials and issues

### ISSUE THREAD

**Issue by sunjoomoon** [edoburu/django-fluent-pages#106]
Template tag for display child menus in the side of the page, I have tried working around following below in the doc. 
```
{% render_menu parent=page max_depth=1 %}
{% render_menu parent='/documentation/' max_depth=1 %}
{% render_menu parent=8 max_depth=1 %}
```
Here are the sample trees, A company menu with child menus.

```
Company
    Background
    Value Proposition
    Media Center
    CSR
    Contact
```

Here are the results.
1) When I click  "Company" then all the child menus are shown in the side bar
2) But then when I click any child menu, ex) Background all the child menus are NOT shown.

So, hope to figure out to have the child menus stay shown no matter which is clicked. Hope that makes sense, any clue as to what to look/configure?

**Comment by vdboor** [comment]
Hi! did you find a solution to the problem?
