### ISSUE TITLE
Fluent Page New Page Type, Page NOT Found issue

### ISSUE THREAD

**Issue by sunjoomoon** [edoburu/django-fluent-pages#107]
Following below tutorials and doc, I am trying out things
```
https://github.com/edoburu/django-fluent-pages/blob/master/docs/newpagetypes/models.rst
http://django-fluent-pages.readthedocs.org/en/latest/newpagetypes/urls.html
```

1) single language  - all went fine and perfect

2) multilanguage - this got me in the corner
2-1) with pk as the url, in list page all fine but when I click the detail page view, below is returned.
```
Page not found (404)
Request Method: 	GET
Request URL: 	http://domain.com/zh-hans/faq/4
Raised by: 	fluent_pages.views.dispatcher.CmsPageDispatcher

No published 'UrlNode' found for the path '/faq/4' (language 'zh-hans', fallback: 'ko').
```

Here is the views.py
```
from faq.models import Faq

def faq_details(request, pk):
    faq = get_object_or_404(Faq, pk=pk)
    return render(request, 'faq/faq_details.html', {
        'faq': faq
    })
```

page_type_plugins.py
```
@page_type_pool.register
class FaqCategoryPagePlugin(PageTypePlugin):
    """"
    A new pagetype plugin that binds the rendering and model together.
    """
    model = FaqCategoryPage
    render_template = "faq/faq_categorypage.html"
    urls = patterns('faq.views',
        url('^/(?P<pk>\d+)/$', 'faq_details'),
    )
```
Seems somehow slug and pk as url is not recognized, what am I missing? Again, this happens only with multilanguage using Parler.

**Comment by vdboor** [comment]
The reason your pattern fail, is because you start with an additional `/`. The slash is already consumed by the page URL itself.

Did you find a solution to this, or did you switch packages?
