### ISSUE TITLE
Missing meta options in 0001 migration.

### ISSUE THREAD

**Issue by mrmachine** [edoburu/django-fluent-pages#109]
Looks like the 0001 migration is slightly out of sync with the model's meta options. We had to add (in our fork):

```python
        migrations.AlterModelOptions(
            name='htmlpagetranslation',
            options={'default_permissions': (), 'verbose_name': 'SEO Translation', 'managed': True, 'verbose_name_plural': 'SEO Translations'},
        ),
```

to the 0001 migration (stolen from an 0002 migration that `makemigrations` produced inside the fluent_pages package). We updated 0001 instead of adding 0002 to avoid our migrations having dependencies on an 0002 migration that doesn't exist upstream.

You could fix it by running makemigrations and adding an 0002 migration, or by editing 0001 as we have done, since the change doesn't touch the database at all, anyone who has already applied 0001 doesn't actually need to apply any migrations.

**Comment by vdboor** [comment]
Thanks for reporting, fixed in ff08d10673cf27f36da30f1f970b4f6b8844cd60!
