### ISSUE TITLE
Idea: Draft pages visible to users who are staff members.

### ISSUE THREAD

**Issue by vinnyrose** [edoburu/django-fluent-pages#54]
i.e. the following would show all pages for staff but only published for regular or anonymous users.

    Page.objects.published(for_user=request.user)

**Comment by vdboor** [comment]
That is a very good idea, I'm still considering the syntax, but in general, I'd like to see this getting added.

**Comment by vinnyrose** [comment]
Any update on preferred syntax for this? I was able to get this to work. Draft pages will load for staff members, and they will also appear in navigation.
