### ISSUE TITLE
Cannot delete fluentpage in admin

### ISSUE THREAD

**Issue by RealBigB** [edoburu/django-fluent-pages#57]
Error message:

    IntegrityError at /admin/fluent_pages/page/2/delete/
    (1451, 'Cannot delete or update a parent row: a foreign key constraint fails 
    (`cms17`.`fluent_contents_contentitem`, CONSTRAINT `ee8c2fd087492bad9ff5ef018852dc50`
    FOREIGN KEY (`placeholder_id`) REFERENCES `fluent_contents_placeholder` (`id`))')

Versions:

Django==1.7.6
MySQL-python==1.2.5
git+https://github.com/edoburu/django-fluent-contents.git@dfe7f762cb4c7203d87c111bc292509bc305fdce
git+https://github.com/edoburu/django-fluent-pages.git@98159bd07226fbec4c3e9683177add7005d3bed8

FWIW in the admin the placeholder is indeed listed after the contentitem:

    Page: Du
    URL Node: /yadda/du/
    URL Node translation: Français: Du
    Contentitem link: 'Texte 3' in 'Français Main'
    Texte: lalala
    Placeholder: Main
    Placeholder: Sidebar

**Comment by RealBigB** [comment]
Ok, known bug in fluent-contents, cf https://github.com/edoburu/django-fluent-contents/issues/19

**Comment by RealBigB** [comment]
FWIW: solved the issue by creating my own fluentpage type based on `fluent_pages.integration.fluent_contents.FluentContentsPage` but I had to manually set `meta.db_table` to meet fluent-pages expectations.

**Comment by vdboor** [comment]
This should be fixed in v1.0, which just appeared on pypi
