### ISSUE TITLE
[django 1.7] django 1.7 migrations - still some issues...

### ISSUE THREAD

**Issue by RealBigB** [edoburu/django-fluent-pages#60]
Using django 1.7.4 and latest versions of fluent:

git+https://github.com/edoburu/django-fluent-utils@906ccbb7fdb7a13da394712b99b72d10a61aa486#egg=django-fluent-utils
git+https://github.com/edoburu/django-fluent-contents.git@7e3cdec7802b8be1eb60a5f00478434ee996e721#egg=django-fluent-contents
git+https://github.com/edoburu/django-fluent-pages.git@199c1f613822cc33c11cf3e287d753cc6ddf8391#egg=django-fluent-pages

makemigrations still wants to add migrations to fluent_pages and oembeditem:

    t$ ./manage.py makemigrations --dry-run
    Migrations for 'fluent_pages':
      0002_auto_20150403_1707.py:
      - Change Meta options on htmlpagetranslation
      - Alter field language_code on htmlpagetranslation
      - Alter field key on urlnode
      - Alter field language_code on urlnode_translation
    Migrations for 'oembeditem':
      0002_auto_20150403_1707.py:
      - Rename table for oembeditem to None

The reference to UrlNode.keys comes from 1.7 migrations wanting to log each and any changes to `field.choices`, and I assume that  it's about the same for `UrlNode.language_code` and `HtmlPageTranslation.language_code`.  Can't understand why it wants to migrate `HtmlPageTranslation.Meta`

wrt/ oembeditem, the problem also exists for UrlNode subclasses so I post it here: the 'fix' around `Meta.db_table` doesn't work as expected, I still have to manually set my UrlNode and ContentItem Meta.db_table manually if I don't want this problem to appear in my own apps.

**Comment by vdboor** [comment]
This has been fixed, you can also use the new official releases now: https://django-fluent.org/blog/2015/04/django-17-and-18-support-here/ :D
