### ISSUE TITLE
Adding custom entries to menu

### ISSUE THREAD

**Issue by cdvv7788** [edoburu/django-fluent-pages#75]
Picture it this way:
I have the cms under /pages/, and i want something under /store/.
Is there a way to add entries to the menu without an associated page? That way i could add the item and point it to a custom url, which in turn can be served by a regular django view. Using the redirect node is not what i want, as it would leave a redirect behind.
I guess this is not hard to implement in case it is not possible by default, just wondering if there is already a way to do it.
Does it make sense?

**Comment by vdboor** [comment]
I guess you've closed this because you've found the solution?

Yes, you can create a new page type, and associate url patterns with it. The example app shows how to do this for a webshop page.
