### ISSUE TITLE
Error: "No published 'UrlNode' found..." when adding pages outside the sitemaps

### ISSUE THREAD

**Issue by sepi2048** [edoburu/django-fluent-pages#81]
I am trying to include https://django-envelope.readthedocs.org/en/latest/usage.html to my django-fluent project.

I have added the envelope form-url "contact" to /django-fluent.org/src/djangofluent/urls.py as described in the django-envelope docs. Sill I keep getting this error: No published 'UrlNode' found for the path '/contact/', language 'en'.

How can I set this new contact-url to published?

**Comment by vdboor** [comment]
I think you've placed the url include below the one that fluent-pages needs. Because the `url(r'', include('fluent_pages.urls'))` acts as a catch-all, you need to place any other url pattern above it.
