### ISSUE TITLE
`fluent_pages.0001_initial` migration makes wrong assumption about `SITE_ID`.

### ISSUE THREAD

**Issue by mrmachine** [edoburu/django-fluent-pages#90]
It assumes that if any `Site` objects exist, that a site matching `settings.SITE_ID` will exist. That's not always true. We have two projects which share the same database, and they have different values for `settings.SITE_ID`.

When I migrate the first project, all good. When I migrate the second project, there is a `Site` object, so this migration doesn't bother creating a new one to match `settings.SITE_ID`, and then I get `django.contrib.sites.models.DoesNotExist: Site matching query does not exist.`

I think it could be fixed by changing the code like this:

```
def make_site(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    Site.objects.get_or_create(
        pk=settings.SITE_ID,
        defaults=dict(
            name='example',
            domain='example.com',
        ))
```

This also applies to https://github.com/edoburu/django-fluent-contents/issues/55

Any objections?

**Comment by vdboor** [comment]
Fully agreed, I've updated this in 9f181066e7461cee49cc5df7ce021fbd756900ce
